### ISSUE TITLE
Is there a perfect method to export background images?

### ISSUE THREAD

**Issue by yihleego** [facebookresearch/AnimatedDrawings#124]
Hi AnimatedDrawings developers,

First let me thank you for this project, it's really great! 🎉🎉🎉

I noticed that it supports background images. And I didn't find the code to export background images in the project, so I added the following code after "save mask":
https://github.com/facebookresearch/AnimatedDrawings/blob/f4ac0eafacc0d0ad38030b6549672f668f1c3b4c/examples/image_to_annotations.py#L139-L142

```python
# save background
full_mask = np.zeros((img.shape[0], img.shape[1]), dtype=np.uint8)
full_mask[t:b, l:r] = mask
background = cv2.inpaint(img, full_mask, 3, cv2.INPAINT_TELEA)
cv2.imwrite(str(outdir/'background.png'), background)
```

Exec cmd:

```bash
python image_to_annotations.py drawings/garlic.png garlic_out
```

The background image is not perfect, so I wonder if there is any example or could you plz add a demo?

<img src="https://user-images.githubusercontent.com/21337386/233023550-66e683d9-f01c-4cdd-81ba-e6095072ed88.png" width="256" height="256"/>
<img src="https://user-images.githubusercontent.com/21337386/233022795-e5b0e850-1eee-4fa7-844d-bcbd464925c6.png" width="256" height="256"/>

_I've never used OpenCV or Torch before, and I only started learning them because of this project, hope my question is not so stupid._

**Comment by hjessmith** [comment]
Thanks for the kind words about the project. Your question is not stupid, don't worry about that.

I created the example background image shown in the readme tutorial using Photoshop's content-aware fill, which is why it looks so good. Most of the free inpainting options out there aren't content-aware (as far as I can tell), so it's difficult to infill a large 2D area, such as the garlic's body, without noticeable artifacts. 

If you DO happen to come across a free content-aware infilling tool (with a permissive license), I'd be happy to add some scripts/examples/demo to this project. It would be quite useful I imagine.

**Comment by yihleego** [comment]
That makes sense ahah, thank you for taking the time to provide such a detailed answer to my question.
I'll try to find that tool/open source code.
