### ISSUE TITLE
CentOS 7 AttributeError: GLFWError:  (65543) b'GLX: Failed to create context: Badlength'

### ISSUE THREAD

**Issue by ADingDing** [facebookresearch/AnimatedDrawings#174]
os： CentOS Linux release 7.9.2009 (Core)
log in to the server without display remotely using ssh
remote tool to show: Xmanager
I meet erro

![errorAnimated](https://github.com/facebookresearch/AnimatedDrawings/assets/30373430/bf5319bc-4611-4b6e-8b20-723217e74024)

**Comment by hjessmith** [comment]
CentOS isn't a supported OS and I haven't encountered this error before. If you do manage to fix it, please share your workaround here.

**Comment by kheedogg** [comment]
How about to try "Export MP4 video" instead of "Quick Start"?

```
from animated_drawings import render
render.start('./examples/config/mvc/export_mp4_example.yaml')
```

It might kinda hard to use window in ssh environment.

[And also you might have to convert the code `USE_MESA: True` in ./animated_drawings/mvc_base_cfg.yaml.](https://github.com/facebookresearch/AnimatedDrawings/tree/main#headless-rendering)
