### ISSUE TITLE
Build Error on TorchServe Docker Image

### ISSUE THREAD

**Issue by chminipark** [facebookresearch/AnimatedDrawings#207]
Hi 🙋‍♂️

I tried to build torchserve docker image. So, I followed exactly same in README. But I’ve got some error on building images

``` bash
#0 14.60       /opt/conda/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
#0 14.60       !!
#0 14.60       
#0 14.60               ********************************************************************************
#0 14.60               Requirements should be satisfied by a PEP 517 installer.
#0 14.60               If you are using pip, you can try `pip install --use-pep517`.
#0 14.60               ********************************************************************************
#0 14.60       
#0 14.60       !!
```

My guess is that this error is due to some deprecated method to update python version
So, I put tag(23.3.1-0) miniconda3 images in dockerfile [TAG LIST](https://hub.docker.com/r/continuumio/miniconda3/tags)

``` bash
# AnimatedDrawings/torchserve/Dockerfile
# Line : 3

FROM continuumio/miniconda3:23.3.1-0
```

And rebuild it, everything work!

My solution is makeshift. There will be a better solution…
For your information, I put entire log in expander control “Error Log”
thanks!

My Server OS : Ubuntu 22.04.2 LTS
<details>
<summary>Error Log</summary>
<div>

``` bash
(animated_drawings) minii@minii-desktop:~/test/AnimatedDrawings/torchserve$ sudo docker build -t docker_torchserve .
[+] Building 17.9s (15/21)                                                                                                                       
 => [internal] load build definition from Dockerfile                                                                                        0.0s
 => => transferring dockerfile: 1.17kB                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                           0.0s
 => => transferring context: 2B                                                                                                             0.0s
 => resolve image config for docker.io/docker/dockerfile:1.2                                                                                1.4s
 => CACHED docker-image://docker.io/docker/dockerfile:1.2@sha256:e2a8561e419ab1ba6b2fe6cbdf49fd92b95912df1cf7d313c3e2230a333fdbcc           0.0s
 => [internal] load build definition from Dockerfile                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                           0.0s
 => [internal] load metadata for docker.io/continuumio/miniconda3:latest                                                                    1.0s
 => [internal] load build context                                                                                                           0.0s
 => => transferring context: 394B                                                                                                           0.0s
 => [ 1/13] FROM docker.io/continuumio/miniconda3@sha256:42cd2ca0ece04579b6127e1a1a0f83c25a079145d408eb65e39206ac05069a77                   0.0s
 => CACHED [ 2/13] RUN mkdir -p /usr/share/man/man1                                                                                         0.0s
 => CACHED [ 3/13] RUN apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y     ca-certificates  0.0s
 => CACHED [ 4/13] RUN pip install openmim                                                                                                  0.0s
 => CACHED [ 5/13] RUN pip install torch                                                                                                    0.0s
 => CACHED [ 6/13] RUN mim install mmcv-full==1.7.0                                                                                         0.0s
 => ERROR [ 7/13] RUN pip install mmpose==0.29.0                                                                                           15.4s
------
 > [ 7/13] RUN pip install mmpose==0.29.0:
#0 0.864 Collecting mmpose==0.29.0
#0 0.926   Downloading mmpose-0.29.0-py2.py3-none-any.whl (1.6 MB)
#0 1.239      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 5.1 MB/s eta 0:00:00
#0 1.283 Collecting chumpy (from mmpose==0.29.0)
#0 1.296   Downloading chumpy-0.70.tar.gz (50 kB)
#0 1.304      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.6/50.6 kB 5.5 MB/s eta 0:00:00
#0 1.309   Preparing metadata (setup.py): started
#0 1.573   Preparing metadata (setup.py): finished with status 'done'
#0 1.605 Collecting json-tricks (from mmpose==0.29.0)
#0 1.618   Downloading json_tricks-3.17.2-py2.py3-none-any.whl (27 kB)
#0 1.766 Collecting matplotlib (from mmpose==0.29.0)
#0 1.779   Downloading matplotlib-3.7.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
#0 2.816      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 11.1 MB/s eta 0:00:00
#0 2.846 Collecting munkres (from mmpose==0.29.0)
#0 2.858   Downloading munkres-1.1.4-py2.py3-none-any.whl (7.0 kB)
#0 2.860 Requirement already satisfied: numpy in /opt/conda/lib/python3.11/site-packages (from mmpose==0.29.0) (1.25.1)
#0 2.861 Requirement already satisfied: opencv-python in /opt/conda/lib/python3.11/site-packages (from mmpose==0.29.0) (4.8.0.74)
#0 2.862 Requirement already satisfied: pillow in /opt/conda/lib/python3.11/site-packages (from mmpose==0.29.0) (10.0.0)
#0 2.968 Collecting scipy (from mmpose==0.29.0)
#0 3.004   Downloading scipy-1.11.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.2 MB)
#0 6.192      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.2/36.2 MB 10.6 MB/s eta 0:00:00
#0 6.270 Collecting torchvision (from mmpose==0.29.0)
#0 6.283   Downloading torchvision-0.15.2-cp311-cp311-manylinux1_x86_64.whl (6.0 MB)
#0 6.839      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 10.9 MB/s eta 0:00:00
#0 7.078 Collecting xtcocotools>=1.12 (from mmpose==0.29.0)
#0 7.293   Downloading xtcocotools-1.13.tar.gz (28 kB)
#0 7.308   Preparing metadata (setup.py): started
#0 12.53   Preparing metadata (setup.py): finished with status 'done'
#0 12.54 Requirement already satisfied: setuptools>=18.0 in /opt/conda/lib/python3.11/site-packages (from xtcocotools>=1.12->mmpose==0.29.0) (67.8.0)
#0 12.73 Collecting cython>=0.27.3 (from xtcocotools>=1.12->mmpose==0.29.0)
#0 12.74   Using cached Cython-3.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
#0 12.81 Collecting contourpy>=1.0.1 (from matplotlib->mmpose==0.29.0)
#0 12.81   Using cached contourpy-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
#0 12.83 Collecting cycler>=0.10 (from matplotlib->mmpose==0.29.0)
#0 12.83   Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
#0 12.89 Collecting fonttools>=4.22.0 (from matplotlib->mmpose==0.29.0)
#0 12.89   Using cached fonttools-4.41.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
#0 12.97 Collecting kiwisolver>=1.0.1 (from matplotlib->mmpose==0.29.0)
#0 12.97   Using cached kiwisolver-1.4.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
#0 12.97 Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib->mmpose==0.29.0) (23.0)
#0 13.01 Collecting pyparsing<3.1,>=2.3.1 (from matplotlib->mmpose==0.29.0)
#0 13.01   Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
#0 13.01 Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.11/site-packages (from matplotlib->mmpose==0.29.0) (2.8.2)
#0 13.03 Requirement already satisfied: six>=1.11.0 in /opt/conda/lib/python3.11/site-packages (from chumpy->mmpose==0.29.0) (1.16.0)
#0 13.06 Requirement already satisfied: requests in /opt/conda/lib/python3.11/site-packages (from torchvision->mmpose==0.29.0) (2.29.0)
#0 13.07 Requirement already satisfied: torch==2.0.1 in /opt/conda/lib/python3.11/site-packages (from torchvision->mmpose==0.29.0) (2.0.1)
#0 13.09 Requirement already satisfied: filelock in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (3.12.2)
#0 13.09 Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (4.7.1)
#0 13.09 Requirement already satisfied: sympy in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (1.12)
#0 13.09 Requirement already satisfied: networkx in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (3.1)
#0 13.09 Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (3.1.2)
#0 13.09 Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (11.7.99)
#0 13.09 Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (11.7.99)
#0 13.09 Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (11.7.101)
#0 13.09 Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (8.5.0.96)
#0 13.10 Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (11.10.3.66)
#0 13.10 Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (10.9.0.58)
#0 13.10 Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (10.2.10.91)
#0 13.10 Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (11.4.0.1)
#0 13.10 Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (11.7.4.91)
#0 13.10 Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (2.14.3)
#0 13.10 Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (11.7.91)
#0 13.10 Requirement already satisfied: triton==2.0.0 in /opt/conda/lib/python3.11/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (2.0.0)
#0 13.11 Requirement already satisfied: wheel in /opt/conda/lib/python3.11/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1->torchvision->mmpose==0.29.0) (0.38.4)
#0 13.20 Requirement already satisfied: cmake in /opt/conda/lib/python3.11/site-packages (from triton==2.0.0->torch==2.0.1->torchvision->mmpose==0.29.0) (3.27.0)
#0 13.20 Requirement already satisfied: lit in /opt/conda/lib/python3.11/site-packages (from triton==2.0.0->torch==2.0.1->torchvision->mmpose==0.29.0) (16.0.6)
#0 13.37 Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests->torchvision->mmpose==0.29.0) (2.0.4)
#0 13.37 Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests->torchvision->mmpose==0.29.0) (3.4)
#0 13.38 Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests->torchvision->mmpose==0.29.0) (1.26.16)
#0 13.38 Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests->torchvision->mmpose==0.29.0) (2023.5.7)
#0 13.48 Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2->torch==2.0.1->torchvision->mmpose==0.29.0) (2.1.3)
#0 13.52 Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.11/site-packages (from sympy->torch==2.0.1->torchvision->mmpose==0.29.0) (1.3.0)
#0 13.66 Building wheels for collected packages: xtcocotools, chumpy
#0 13.66   Building wheel for xtcocotools (setup.py): started
#0 14.60   Building wheel for xtcocotools (setup.py): finished with status 'error'
#0 14.60   error: subprocess-exited-with-error
#0 14.60   
#0 14.60   × python setup.py bdist_wheel did not run successfully.
#0 14.60   │ exit code: 1
#0 14.60   ╰─> [36 lines of output]
#0 14.60       /opt/conda/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
#0 14.60       !!
#0 14.60       
#0 14.60               ********************************************************************************
#0 14.60               Requirements should be satisfied by a PEP 517 installer.
#0 14.60               If you are using pip, you can try `pip install --use-pep517`.
#0 14.60               ********************************************************************************
#0 14.60       
#0 14.60       !!
#0 14.60         dist.fetch_build_eggs(dist.setup_requires)
#0 14.60       running bdist_wheel
#0 14.60       running build
#0 14.60       running build_py
#0 14.60       creating build
#0 14.60       creating build/lib.linux-x86_64-cpython-311
#0 14.60       creating build/lib.linux-x86_64-cpython-311/xtcocotools
#0 14.60       copying xtcocotools/mask.py -> build/lib.linux-x86_64-cpython-311/xtcocotools
#0 14.60       copying xtcocotools/cocoeval.py -> build/lib.linux-x86_64-cpython-311/xtcocotools
#0 14.60       copying xtcocotools/version.py -> build/lib.linux-x86_64-cpython-311/xtcocotools
#0 14.60       copying xtcocotools/__init__.py -> build/lib.linux-x86_64-cpython-311/xtcocotools
#0 14.60       copying xtcocotools/coco.py -> build/lib.linux-x86_64-cpython-311/xtcocotools
#0 14.60       running build_ext
#0 14.60       Compiling xtcocotools/_mask.pyx because it changed.
#0 14.60       [1/1] Cythonizing xtcocotools/_mask.pyx
#0 14.60       /tmp/pip-install-_2cyb3ra/xtcocotools_0bbdb5ac63e7425a8e14d903596d6452/.eggs/Cython-3.0.0-py3.11-linux-x86_64.egg/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-_2cyb3ra/xtcocotools_0bbdb5ac63e7425a8e14d903596d6452/xtcocotools/_mask.pyx
#0 14.60         tree = Parsing.p_module(s, pxd, full_module_name)
#0 14.60       building 'xtcocotools._mask' extension
#0 14.60       creating build/common
#0 14.60       creating build/temp.linux-x86_64-cpython-311
#0 14.60       creating build/temp.linux-x86_64-cpython-311/common
#0 14.60       creating build/temp.linux-x86_64-cpython-311/xtcocotools
#0 14.60       gcc -pthread -B /opt/conda/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/opt/conda/lib/python3.11/site-packages/numpy/core/include -I./common -I/opt/conda/include/python3.11 -c ../common/maskApi.c -o build/temp.linux-x86_64-cpython-311/../common/maskApi.o
#0 14.60       gcc: error: ../common/maskApi.c: No such file or directory
#0 14.60       gcc: fatal error: no input files
#0 14.60       compilation terminated.
#0 14.60       error: command '/usr/bin/gcc' failed with exit code 1
#0 14.60       [end of output]
#0 14.60   
#0 14.60   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 14.60   ERROR: Failed building wheel for xtcocotools
#0 14.60   Running setup.py clean for xtcocotools
#0 14.86   Building wheel for chumpy (setup.py): started
#0 15.18   Building wheel for chumpy (setup.py): finished with status 'done'
#0 15.18   Created wheel for chumpy: filename=chumpy-0.70-py3-none-any.whl size=58267 sha256=ead2a61fb47398bd975ad120f30aec23d4b6f4a3628a0d9e8f2edc86fd04aa0e
#0 15.18   Stored in directory: /root/.cache/pip/wheels/91/96/31/3e16aa7084783b2e57a81bb9a7fa3598d32445a964b1692259
#0 15.18 Successfully built chumpy
#0 15.18 Failed to build xtcocotools
#0 15.18 ERROR: Could not build wheels for xtcocotools, which is required to install pyproject.toml-based projects
------
Dockerfile:24
--------------------
  22 |     RUN pip install torch
  23 |     RUN mim install mmcv-full==1.7.0
  24 | >>> RUN pip install mmpose==0.29.0
  25 |     RUN pip install mmdet==2.27.0
  26 |     RUN pip install torchserve
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install mmpose==0.29.0" did not complete successfully: exit code: 1
```

</div>
</details>

**Comment by stellaluminary** [comment]
I have same issue.
But after modifying 'FROM continuumio/miniconda3' to 'FROM continuumio/miniconda3:23.3.1-0' in dockerfile, it works well. 
Thanks @chminipark

**Comment by mksoo** [comment]
I am experiencing the same issue. 
But, sadly, fixing the line in the dockerfile doesn't solve the issue.

My OS: Mac(M1) 13.4.1

<details><summary>here is my log</summary>
<p>
 > [ 7/13] RUN pip install mmpose==0.29.0:                                                                                       
0.531 Collecting mmpose==0.29.0
0.581   Downloading mmpose-0.29.0-py2.py3-none-any.whl (1.6 MB)
0.644      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 26.3 MB/s eta 0:00:00
0.670 Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from mmpose==0.29.0) (1.25.2)
0.690 Collecting xtcocotools>=1.12
0.701   Downloading xtcocotools-1.13.tar.gz (28 kB)
0.706   Preparing metadata (setup.py): started
4.852   Preparing metadata (setup.py): finished with status 'done'
4.873 Collecting json-tricks
4.884   Downloading json_tricks-3.17.2-py2.py3-none-any.whl (27 kB)
4.929 Collecting torchvision
4.942   Downloading torchvision-0.15.2-cp310-cp310-manylinux2014_aarch64.whl (1.2 MB)
4.978      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 35.6 MB/s eta 0:00:00
5.073 Collecting scipy
5.082   Downloading scipy-1.11.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (32.8 MB)
5.919      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.8/32.8 MB 30.3 MB/s eta 0:00:00
6.065 Collecting matplotlib
6.084   Using cached matplotlib-3.7.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (11.4 MB)
6.108 Requirement already satisfied: pillow in /opt/conda/lib/python3.10/site-packages (from mmpose==0.29.0) (10.0.0)
6.121 Collecting munkres
6.132   Downloading munkres-1.1.4-py2.py3-none-any.whl (7.0 kB)
6.134 Requirement already satisfied: opencv-python in /opt/conda/lib/python3.10/site-packages (from mmpose==0.29.0) (4.8.0.74)
6.149 Collecting chumpy
6.157   Downloading chumpy-0.70.tar.gz (50 kB)
6.160      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.6/50.6 kB 26.5 MB/s eta 0:00:00
6.164   Preparing metadata (setup.py): started
6.411   Preparing metadata (setup.py): finished with status 'done'
6.415 Requirement already satisfied: setuptools>=18.0 in /opt/conda/lib/python3.10/site-packages (from xtcocotools>=1.12->mmpose==0.29.0) (60.2.0)
6.595 Collecting cython>=0.27.3
6.598   Using cached Cython-3.0.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (3.4 MB)
6.663 Collecting contourpy>=1.0.1
6.664   Using cached contourpy-1.1.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (283 kB)
6.701 Collecting kiwisolver>=1.0.1
6.703   Using cached kiwisolver-1.4.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.4 MB)
6.706 Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib->mmpose==0.29.0) (23.0)
6.718 Collecting cycler>=0.10
6.719   Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
6.747 Collecting pyparsing<3.1,>=2.3.1
6.747   Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
6.749 Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.10/site-packages (from matplotlib->mmpose==0.29.0) (2.8.2)
6.810 Collecting fonttools>=4.22.0
6.813   Using cached fonttools-4.42.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.4 MB)
6.836 Requirement already satisfied: six>=1.11.0 in /opt/conda/lib/python3.10/site-packages (from chumpy->mmpose==0.29.0) (1.16.0)
6.861 Requirement already satisfied: torch==2.0.1 in /opt/conda/lib/python3.10/site-packages (from torchvision->mmpose==0.29.0) (2.0.1)
6.861 Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from torchvision->mmpose==0.29.0) (2.28.2)
6.865 Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (1.12)
6.865 Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (3.1)
6.865 Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (4.7.1)
6.865 Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (3.1.2)
6.866 Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch==2.0.1->torchvision->mmpose==0.29.0) (3.12.2)
6.905 Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->torchvision->mmpose==0.29.0) (2.0.4)
6.905 Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->torchvision->mmpose==0.29.0) (3.4)
6.905 Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->torchvision->mmpose==0.29.0) (1.26.15)
6.906 Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->torchvision->mmpose==0.29.0) (2022.12.7)
6.926 Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch==2.0.1->torchvision->mmpose==0.29.0) (2.1.3)
6.937 Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch==2.0.1->torchvision->mmpose==0.29.0) (1.3.0)
6.958 Building wheels for collected packages: xtcocotools, chumpy
6.959   Building wheel for xtcocotools (setup.py): started
7.942   Building wheel for xtcocotools (setup.py): finished with status 'error'
7.946   error: subprocess-exited-with-error
7.946   
7.946   × python setup.py bdist_wheel did not run successfully.
7.946   │ exit code: 1
7.946   ╰─> [27 lines of output]
7.946       /opt/conda/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
7.946         warnings.warn(
7.946       running bdist_wheel
7.946       running build
7.946       running build_py
7.946       creating build
7.946       creating build/lib.linux-aarch64-3.10
7.946       creating build/lib.linux-aarch64-3.10/xtcocotools
7.946       copying xtcocotools/cocoeval.py -> build/lib.linux-aarch64-3.10/xtcocotools
7.946       copying xtcocotools/__init__.py -> build/lib.linux-aarch64-3.10/xtcocotools
7.946       copying xtcocotools/coco.py -> build/lib.linux-aarch64-3.10/xtcocotools
7.946       copying xtcocotools/version.py -> build/lib.linux-aarch64-3.10/xtcocotools
7.946       copying xtcocotools/mask.py -> build/lib.linux-aarch64-3.10/xtcocotools
7.946       running build_ext
7.946       Compiling xtcocotools/_mask.pyx because it changed.
7.946       [1/1] Cythonizing xtcocotools/_mask.pyx
7.946       /tmp/pip-install-_au18max/xtcocotools_130116a7714c41b7be13b04fe8a9428e/.eggs/Cython-3.0.0-py3.10-linux-aarch64.egg/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-_au18max/xtcocotools_130116a7714c41b7be13b04fe8a9428e/xtcocotools/_mask.pyx
7.946         tree = Parsing.p_module(s, pxd, full_module_name)
7.946       creating build/common
7.946       creating build/temp.linux-aarch64-3.10
7.946       creating build/temp.linux-aarch64-3.10/common
7.946       creating build/temp.linux-aarch64-3.10/xtcocotools
7.946       gcc -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O3 -Wall -fPIC -O3 -isystem /opt/conda/include -fPIC -O3 -isystem /opt/conda/include -fPIC -I/opt/conda/lib/python3.10/site-packages/numpy/core/include -I./common -I/opt/conda/include/python3.10 -c ../common/maskApi.c -o build/temp.linux-aarch64-3.10/../common/maskApi.o
7.946       gcc: error: ../common/maskApi.c: No such file or directory
7.946       gcc: fatal error: no input files
7.946       compilation terminated.
7.946       error: command '/usr/bin/gcc' failed with exit code 1
7.946       [end of output]
7.946   
7.946   note: This error originates from a subprocess, and is likely not a problem with pip.
7.946   ERROR: Failed building wheel for xtcocotools
7.946   Running setup.py clean for xtcocotools
8.171   Building wheel for chumpy (setup.py): started
8.429   Building wheel for chumpy (setup.py): finished with status 'done'
8.429   Created wheel for chumpy: filename=chumpy-0.70-py3-none-any.whl size=58286 sha256=9bfe2e3dc4e857287c371aea02c6798f6c1e48a32e5a684685c1ce16e7f9023c
8.429   Stored in directory: /root/.cache/pip/wheels/e0/c1/ef/29ba7be03653a29ef6f2c3e1956d6c4d8877f2b243af411db1
8.430 Successfully built chumpy
8.431 Failed to build xtcocotools
8.644 Installing collected packages: munkres, json-tricks, scipy, pyparsing, kiwisolver, fonttools, cython, cycler, contourpy, matplotlib, chumpy, xtcocotools, torchvision, mmpose
12.21   Running setup.py install for xtcocotools: started
12.95   Running setup.py install for xtcocotools: finished with status 'error'
12.95   error: subprocess-exited-with-error
12.95   
12.95   × Running setup.py install for xtcocotools did not run successfully.
12.95   │ exit code: 1
12.95   ╰─> [25 lines of output]
12.95       running install
12.95       /opt/conda/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
12.95         warnings.warn(
12.95       running build
12.95       running build_py
12.95       creating build/lib.linux-aarch64-3.10
12.95       creating build/lib.linux-aarch64-3.10/xtcocotools
12.95       copying xtcocotools/cocoeval.py -> build/lib.linux-aarch64-3.10/xtcocotools
12.95       copying xtcocotools/__init__.py -> build/lib.linux-aarch64-3.10/xtcocotools
12.95       copying xtcocotools/coco.py -> build/lib.linux-aarch64-3.10/xtcocotools
12.95       copying xtcocotools/version.py -> build/lib.linux-aarch64-3.10/xtcocotools
12.95       copying xtcocotools/mask.py -> build/lib.linux-aarch64-3.10/xtcocotools
12.95       running build_ext
12.95       Compiling xtcocotools/_mask.pyx because it depends on /opt/conda/lib/python3.10/site-packages/Cython/Includes/libc/string.pxd.
12.95       [1/1] Cythonizing xtcocotools/_mask.pyx
12.95       /opt/conda/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-_au18max/xtcocotools_130116a7714c41b7be13b04fe8a9428e/xtcocotools/_mask.pyx
12.95         tree = Parsing.p_module(s, pxd, full_module_name)
12.95       creating build/temp.linux-aarch64-3.10
12.95       creating build/temp.linux-aarch64-3.10/common
12.95       creating build/temp.linux-aarch64-3.10/xtcocotools
12.95       gcc -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O3 -Wall -fPIC -O3 -isystem /opt/conda/include -fPIC -O3 -isystem /opt/conda/include -fPIC -I/opt/conda/lib/python3.10/site-packages/numpy/core/include -I./common -I/opt/conda/include/python3.10 -c ../common/maskApi.c -o build/temp.linux-aarch64-3.10/../common/maskApi.o
12.95       gcc: error: ../common/maskApi.c: No such file or directory
12.95       gcc: fatal error: no input files
12.95       compilation terminated.
12.95       error: command '/usr/bin/gcc' failed with exit code 1
12.95       [end of output]
12.95   
12.95   note: This error originates from a subprocess, and is likely not a problem with pip.
12.96 error: legacy-install-failure
12.96 
12.96 × Encountered error while trying to install package.
12.96 ╰─> xtcocotools
12.96 
12.96 note: This is an issue with the package mentioned above, not pip.
12.96 hint: See above for output from the failure.
------
Dockerfile:25
--------------------
  23 |     RUN mim install mmcv-full==1.7.0
  24 |     
  25 | >>> RUN pip install mmpose==0.29.0
  26 |     RUN pip install mmdet==2.27.0
  27 |     RUN pip install torchserve
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install mmpose==0.29.0" did not complete successfully: exit code: 1
</p>
</details>

**Comment by cyfyv** [comment]
> 我遇到了同样的问题。 但是，遗憾的是，修复 dockerfile 中的行并不能解决问题。
> 
> 我的操作系统：Mac(M1) 13.4.1
> 
> 这是我的日志

我也是这个报错请问解决了么

**Comment by gaoshangle** [comment]
> 我也是这个报错请问解决了么

我也是这个报错请问解决了么

**Comment by hjessmith** [comment]
@mksoo @cyfyv @gaoshangle 

I've just pushed a commit that addresses this, see 361a907. Please try again and let me know if you're still running into problems.
