### ISSUE TITLE
Server response problem

### ISSUE THREAD

**Issue by tigran-sargsyan-w** [facebookresearch/AnimatedDrawings#248]
I would like to make my own animation and installed everything according to the recommendations and instructions that are on the page
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/97106041/61d1763d-e732-4042-a9e2-f2b5d7b04ff0)
and here is my docker container running As seen in the image
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/97106041/d153b613-00e4-4c08-916f-6eb56457a4de)
And now I move on to the point where I need to check the response from the server with command - curl http://localhost:8080/ping
but unfortunately I don't receive any response from the server
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/97106041/7b50c855-df48-4925-b902-aecc15b1bad7)
I thought that maybe my computer was weak and I would have to wait a little longer, but I waited more than 5 minutes and realized that this problem was probably not related to the power of the computer, but to something else

**Comment by Andy-Ren** [comment]
maybe, your docker running is not well;   
you can see log ,through : docker logs <container id>

**Comment by hjessmith** [comment]
Check and see if Torchserve still returns 'healthy' after you've queried it with Animated Drawings. My hunch is that it's dying during the query because it doesn't have enough resources. Please check some of the other closed issues pertaining to Torchserve on the github project to see how other users have handled this.
