### ISSUE TITLE
Issue when running image_to_animation

### ISSUE THREAD

**Issue by rohit123sinha456** [facebookresearch/AnimatedDrawings#251]
Docker image is running fine
![curl](https://github.com/facebookresearch/AnimatedDrawings/assets/41671983/a209be7a-b559-4dae-bd11-920d5d5d6b9e)

But when running image_to_animation I get
![i2a](https://github.com/facebookresearch/AnimatedDrawings/assets/41671983/8c907d84-a64d-41ba-96a9-d86166c01a90)

 and the docker logs looks like
![docker_logs](https://github.com/facebookresearch/AnimatedDrawings/assets/41671983/efde9ed0-90a6-4024-bee4-98dfd9cf08a7)

Please help, on how to resolve this issue.

**Comment by hjessmith** [comment]
Check and see if Torchserve still returns 'healthy' after you've queried it with Animated Drawings. My hunch is that it's dying during the query because it doesn't have enough resources. Please check some of the other closed issues pertaining to Torchserve on the github project to see how other users have handled this.
